# This is a basic workflow to help you get started with Actions

name: Automatic Build

# Controls when the workflow will run
on:
  schedule:
    - cron: "39 20 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_daily:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Daily image build
        uses: VaultVulp/gp-docker-action@1.6.0
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            image-name: nextcloud
            extract-git-tag: false
            additional-image-tags: 27 27.1.3
            custom-args: --platform=linux/arm64,linux/amd64

