# This is a basic workflow to help you get started with Actions

name: Daily build

env:
  NEXTCLOUD_UPSTREAM_VERSION: 27.1.10
  IMAGE_MAJOR_VERSION: 27

# Controls when the workflow will run
on:
  schedule:
    - cron: "39 20 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  weekly_build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        name: Weekly build
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: NEXTCLOUD_UPSTREAM_VERSION=${{ env.NEXTCLOUD_UPSTREAM_VERSION }}
          tags: |
            ghcr.io/0ranki/nextcloud-previews/nextcloud:${{ env.NEXTCLOUD_UPSTREAM_VERSION }}
            ghcr.io/0ranki/nextcloud-previews/nextcloud:${{ env.IMAGE_MAJOR_VERSION }}
            ghcr.io/0ranki/nextcloud-previews/nextcloud:latest
            ghcr.io/0ranki/nextcloud-previews:${{ env.NEXTCLOUD_UPSTREAM_VERSION }}
            ghcr.io/0ranki/nextcloud-previews:${{ env.IMAGE_MAJOR_VERSION }}
            ghcr.io/0ranki/nextcloud-previews:latest
